---
title: Verwijderen en herstellen in Scratch
hero_image: images/banner.png
description: scratch-verwijder beschrijving
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - title: Inleiding
