---
title: Dileu ac adfer yn Scratch
hero_image: images/banner.png
description: Dileu ac adfer yn Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - 
    title: Cyflwyniad
