---
title: Excluindo e restaurando no Scratch
hero_image: images/banner.png
description: scratch-delete descrição
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - 
    title: Introdução
