---
title: Eliminar y restaurar en Scratch
hero_image: images/banner.png
description: descripción de como eliminar en Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - title: Introducción
