---
title: Supprimer et restaurer dans Scratch
hero_image: images/banner.png
description: description supprimer-scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-12-09"
steps:
  - title: Introduction
